import { useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { WideShell } from '../../components/layout/WideShell'
import { usePHC } from '../../store/phcStore'
import { Printer, ArrowLeft, ClipboardList, Activity, AlertCircle, Calendar } from 'lucide-react'
import { LoadingState, EmptyState, cx, Logo } from '../../components/ui'

export default function PHCReportDetail() {
  const { id } = useParams()
  const nav = useNavigate()
  const { currentReport: r, loading, fetchReport } = usePHC()

  useEffect(() => {
    if (id) fetchReport(id)
  }, [fetchReport, id])

  const handlePrint = () => {
    window.print()
  }

  if (loading.currentReport && !r) {
    return (
      <WideShell>
        <div className="flex h-64 items-center justify-center"><LoadingState /></div>
      </WideShell>
    )
  }

  if (!r) {
    return (
      <WideShell>
        <EmptyState icon={ClipboardList} title="Report Not Found" body="The screening report you requested could not be found." />
      </WideShell>
    )
  }

  return (
    <WideShell>
      {/* Top Action Bar (Hidden in Print) */}
      <div className="mb-6 flex items-center justify-between print:hidden">
        <button onClick={() => nav('/reports')} className="flex items-center gap-2 text-[14px] font-semibold text-secondary hover:text-ink transition-colors">
          <ArrowLeft size={18} /> Back to Reports
        </button>
        <button onClick={handlePrint} className="flex items-center gap-2 px-4 py-2 bg-primary text-white font-semibold text-[14px] rounded-[10px] hover:bg-primary-dark transition-colors shadow-sm">
          <Printer size={18} /> Print Report
        </button>
      </div>

      {/* Printable Report Container */}
      <div className="bg-white rounded-[16px] shadow-[0_1px_3px_rgba(15,23,42,0.04)] border border-border p-8 md:p-12 max-w-[900px] mx-auto print:shadow-none print:border-0 print:p-0">
        
        {/* Report Header */}
        <div className="flex items-start justify-between border-b border-border pb-6 mb-8">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <Logo size={28} />
              <span className="font-bold text-[20px] text-ink tracking-tight">SAATHI</span>
            </div>
            <h1 className="text-[24px] font-bold text-ink leading-tight">Osteoarthritis Screening Report</h1>
            <p className="text-[14px] text-secondary mt-1">Generated by SAATHI Field Assessment</p>
          </div>
          <div className="text-right text-[13px] text-secondary">
            <p><strong>Report ID:</strong> <span className="font-mono text-ink">{r.id.split('-')[0]}</span></p>
            <p><strong>Date:</strong> <span className="text-ink">{new Date(r.createdAt).toLocaleDateString()}</span></p>
          </div>
        </div>

        {/* 1. Patient Information */}
        <section className="mb-8">
          <h2 className="text-[13px] font-bold text-secondary uppercase tracking-wider mb-4 border-b border-border pb-2">Patient Information</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-y-4 gap-x-6">
            <div>
              <div className="text-[12px] text-secondary mb-1">Name</div>
              <div className="text-[15px] font-semibold text-ink">{r.patient?.name}</div>
            </div>
            <div>
              <div className="text-[12px] text-secondary mb-1">Age / Sex</div>
              <div className="text-[15px] font-medium text-ink">{r.patient?.age} yrs / {r.patient?.sex}</div>
            </div>
            <div>
              <div className="text-[12px] text-secondary mb-1">Village</div>
              <div className="text-[15px] font-medium text-ink">{r.patient?.village}</div>
            </div>
            <div>
              <div className="text-[12px] text-secondary mb-1">Health ID</div>
              <div className="text-[15px] font-medium text-ink">{r.patient?.healthId || 'N/A'}</div>
            </div>
            <div>
              <div className="text-[12px] text-secondary mb-1">Phone</div>
              <div className="text-[15px] font-medium text-ink">{r.patient?.phone || 'N/A'}</div>
            </div>
            <div>
              <div className="text-[12px] text-secondary mb-1">Occupation</div>
              <div className="text-[15px] font-medium text-ink">{r.patient?.occupation || 'N/A'}</div>
            </div>
          </div>
        </section>

        {/* 2. Screening Information */}
        <section className="mb-8">
          <h2 className="text-[13px] font-bold text-secondary uppercase tracking-wider mb-4 border-b border-border pb-2">Screening Details</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-y-4 gap-x-6">
            <div>
              <div className="text-[12px] text-secondary mb-1">Field Worker</div>
              <div className="text-[15px] font-medium text-ink">{r.worker?.name}</div>
            </div>
            <div>
              <div className="text-[12px] text-secondary mb-1">Joint Screened</div>
              <div className="text-[15px] font-medium text-ink capitalize">{r.joint}</div>
            </div>
            <div>
              <div className="text-[12px] text-secondary mb-1">Side</div>
              <div className="text-[15px] font-medium text-ink capitalize">{r.side}</div>
            </div>
          </div>
        </section>

        {/* 3. Screening Indication */}
        <section className="mb-8 bg-[#F7FAFA] p-6 rounded-[12px] border border-border print:border-ink print:bg-white">
          <h2 className="text-[13px] font-bold text-secondary uppercase tracking-wider mb-3">Screening Indication</h2>
          <div className="flex items-center gap-4">
            <div className={cx(
              "px-4 py-2 rounded-[8px] font-bold text-[16px] uppercase tracking-wide",
              r.result?.band === 'higher' ? 'bg-error-tint text-error-text' :
              r.result?.band === 'moderate' ? 'bg-warning-tint text-warning-text' :
              r.result?.band === 'low' ? 'bg-mint text-primary-dark' : 'bg-gray-100 text-gray-600'
            )}>
              {r.result?.band || 'Unknown'}
            </div>
            <div className="text-[14px] text-ink flex-1">
              {r.result?.band === 'higher' && <span className="font-semibold text-error-text flex items-center gap-1.5"><AlertCircle size={16}/> Further clinical evaluation recommended.</span>}
              {r.result?.band === 'moderate' && <span>Moderate screening risk indicated. Follow-up may be advised.</span>}
              {r.result?.band === 'low' && <span>Low screening risk indicated.</span>}
            </div>
          </div>
          <p className="text-[12px] text-secondary mt-3">
            <strong>Note:</strong> This is a field screening indication, not a clinical diagnosis. It is intended to guide PHC triaging and follow-up care.
          </p>
        </section>

        {/* 4. Key Measured Findings - 5 checks */}
        <section className="mb-8">
          <h2 className="text-[13px] font-bold text-secondary uppercase tracking-wider mb-4 border-b border-border pb-2">Key Measured Findings - 5 checks</h2>
          <div className="bg-white border border-border rounded-[12px] overflow-hidden">
            <table className="w-full text-left text-[14px]">
              <tbody className="divide-y divide-border">
                {r.movement?.performed && (
                  <>
                    <tr className="hover:bg-[#F7FAFA]">
                      <td className="px-4 py-3 font-medium text-ink w-2/3">Range of movement</td>
                      <td className="px-4 py-3 text-secondary">≈ {r.movement.rangeOfMotionDeg}°</td>
                    </tr>
                    <tr className="hover:bg-[#F7FAFA]">
                      <td className="px-4 py-3 font-medium text-ink w-2/3">Movement pattern</td>
                      <td className="px-4 py-3 text-secondary">{r.movement.smoothness >= 0.6 ? 'Even' : 'Uneven'}</td>
                    </tr>
                  </>
                )}
                {r.answers && (
                  <>
                    <tr className="hover:bg-[#F7FAFA]">
                      <td className="px-4 py-3 font-medium text-ink w-2/3">Pain during activity</td>
                      <td className="px-4 py-3 text-secondary">{r.answers['pain_activity'] >= 2 ? 'Yes' : 'No'}</td>
                    </tr>
                    <tr className="hover:bg-[#F7FAFA]">
                      <td className="px-4 py-3 font-medium text-ink w-2/3">Morning stiffness</td>
                      <td className="px-4 py-3 text-secondary">{r.answers['stiffness'] === 3 ? 'More than 30 minutes' : r.answers['stiffness'] === 2 ? 'Less than 30 minutes' : 'No stiffness'}</td>
                    </tr>
                    <tr className="hover:bg-[#F7FAFA]">
                      <td className="px-4 py-3 font-medium text-ink w-2/3">Difficulty with daily tasks</td>
                      <td className="px-4 py-3 text-secondary">{r.answers['function'] === 3 ? 'Cannot do it' : r.answers['function'] === 2 ? 'Very hard' : r.answers['function'] === 1 ? 'A little hard' : 'Not hard'}</td>
                    </tr>
                  </>
                )}
              </tbody>
            </table>
          </div>
        </section>

        {/* 5. All Symptoms */}
        <section className="mb-8">
          <h2 className="text-[13px] font-bold text-secondary uppercase tracking-wider mb-4 border-b border-border pb-2">All Symptoms</h2>
          {r.answers && Object.keys(r.answers).length > 0 ? (
            <div className="bg-white border border-border rounded-[12px] overflow-hidden">
              <table className="w-full text-left text-[14px]">
                <tbody className="divide-y divide-border">
                  {Object.entries(r.answers).map(([key, value]) => (
                    <tr key={key} className="hover:bg-[#F7FAFA]">
                      <td className="px-4 py-3 font-medium text-ink w-2/3">{key.replace(/([A-Z])/g, ' $1').replace(/^./, str => (str as string).toUpperCase())}</td>
                      <td className="px-4 py-3 text-secondary">{String(value)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <p className="text-[14px] text-secondary italic">Symptom questionnaire data not available.</p>
          )}
        </section>

        {/* 6. AI Assessment */}
        <section className="mb-8">
          <h2 className="text-[13px] font-bold text-secondary uppercase tracking-wider mb-4 border-b border-border pb-2">AI Assessment</h2>
          {r.result?.aiModel ? (
            <div className="bg-[#F7FAFA] p-4 rounded-[12px] border border-border text-[14px]">
               <p className="text-ink mb-1"><strong>Model:</strong> {r.result.aiModel}</p>
               <p className="text-secondary">AI assessment completed and incorporated into final screening indication.</p>
            </div>
          ) : (
            <p className="text-[14px] text-secondary italic">AI assessment data not available yet.</p>
          )}
        </section>

        {/* 7. Follow-up */}
        <section>
          <h2 className="text-[13px] font-bold text-secondary uppercase tracking-wider mb-4 border-b border-border pb-2">Follow-up</h2>
          {r.followUpDate ? (
            <div className="flex items-center gap-3 p-4 bg-amber-50/50 rounded-[12px] border border-amber-200 print:border-ink print:bg-white">
               <Calendar size={20} className="text-amber-600" />
               <div>
                 <p className="text-[14px] font-semibold text-ink">Follow-up Due: {new Date(r.followUpDate).toLocaleDateString()}</p>
                 <p className="text-[13px] text-secondary">A clinical evaluation or follow-up screening is scheduled.</p>
               </div>
            </div>
          ) : (
            <p className="text-[14px] text-secondary italic">No follow-up scheduled.</p>
          )}
        </section>
        
      </div>
    </WideShell>
  )
}
